### PR TITLE
Fix nav bar

### LINKED ISSUE #57: Responsive design and implementation

### LINKED ISSUE #62: Change github icon color on hover

### LINKED ISSUE #69: Add its corresponding link to each  button

### PR DESCRIPTION
**Pull request by gabaldon**
close #62
close #57
close #69

### CODE REVIEW

**Comment by Tommytrg** [comment]
Could you rename "Community.svg" as "community.svg"?

File: components/DecentralizedOracle.vue [hunk 1]
```diff
@@ -14,15 +14,17 @@
...
+            }}</Button>
+          </a>
         </div>
         <div class="vertical-line" />
         <div class="right">
           <TestimonialCard
-            v-for="testimonial in testimonials"
-            :key="testimonial.author"
+            v-for="(testimonial, index) in testimonials"
+            :key="index"
```
Comment (Tommytrg) [inline components/DecentralizedOracle.vue:27]: We should avoid using `index` as `key`

File: components/Footer.vue [hunk 2]
```diff
@@ -3,46 +3,104 @@
...
-      <div>
-        <i18n path="footer.copyright.base" class="copyright" tag="p">
-          <span>{{ $t('footer.copyright.witnet_foundation') }}</span>
-          <span>{{ $t('footer.copyright.license') }}</span>
+      <div class="alliance-text">
+        <img
+          class="logo"
+          src="@/assets/images/ado_member.png"
+          alt=""
+          aria-hidden="true"
```
Comment (Tommytrg) [inline components/Footer.vue:51]:
```suggestion
          alt="Witnet is an ADO member"
```

File: components/cards/EcosystemCard.vue [hunk 3]
```diff
@@ -40,14 +46,13 @@ export default {
   display: grid;
   grid-template-rows: auto auto auto;
   grid-template-columns: 250px;
-  justify-items: center;
```
Comment (Tommytrg) [inline components/cards/EcosystemCard.vue:43]: Removing this rule the image is not aligned

File: components/NavBar.vue [hunk 4]
```diff
@@ -27,37 +31,42 @@
       </div>
       <transition name="dropdown" class="dropdown">
         <ul class="tab-container" :class="{ visible: isMenuVisible }">
-          <li class="link">
-            <nuxt-link to="/about" class="tab" @click.native="closeMenu">
+          <li class="link" @click="hideMenu">
+            <InnerLink class="tab" hash="oracle">
```
Comment (Tommytrg) [inline components/NavBar.vue:35]:
```suggestion
            <NavBarLink class="tab" hash="oracle">
```

File: components/cards/EcosystemCard.vue [hunk 5]
```diff
@@ -1,20 +1,26 @@
...
+  <a :href="link" target="_blank">
+    <div :class="border ? 'card-container border' : 'card-container'">
+      <img
+        class="logo"
+        :class="{ auto: border }"
+        :src="src"
+        alt=""
+        aria-hidden="true"
+      />
+      <h3 :class="border ? 'title border' : 'title'">{{ title }}</h3>
```
Comment (Tommytrg) [inline components/cards/EcosystemCard.vue:11]:
```suggestion
      <h3 class="title" :class="{ border }">{{ title }}</h3>
```

File: components/cards/EcosystemCard.vue [hunk 6]
```diff
@@ -1,20 +1,26 @@
...
+      <p :class="border ? 'subtitle border' : 'subtitle'">{{ content }}</p>
```
Comment (Tommytrg) [inline components/cards/EcosystemCard.vue:12]:
```suggestion
      <p class="subtitle" :class="{ border }">{{ content }}</p>
```
